### ISSUE TITLE
ModuleNotFoundError in fresh installation with python 3.12

### ISSUE THREAD

**Issue by alexschroeter** [arkitektio/arkitekt#10]
Tried a fresh install but I get this error with python 3.12.

```
(arkitekt) aschroeter@Moriarty:~$ arkitekt
Traceback (most recent call last):
  File "/home/aschroeter/mambaforge/envs/arkitekt/bin/arkitekt", line 5, in <module>
    from arkitekt.cli.main import cli
  File "/home/aschroeter/mambaforge/envs/arkitekt/lib/python3.12/site-packages/arkitekt/__init__.py", line 1, in <module>
    from arkitekt.apps import Arkitekt
  File "/home/aschroeter/mambaforge/envs/arkitekt/lib/python3.12/site-packages/arkitekt/apps/__init__.py", line 1, in <module>
    from .default import Arkitekt
  File "/home/aschroeter/mambaforge/envs/arkitekt/lib/python3.12/site-packages/arkitekt/apps/default.py", line 1, in <module>
    from arkitekt.apps.connected import ConnectedApp
  File "/home/aschroeter/mambaforge/envs/arkitekt/lib/python3.12/site-packages/arkitekt/apps/connected.py", line 1, in <module>
    from arkitekt.apps.mikro import MikroApp
  File "/home/aschroeter/mambaforge/envs/arkitekt/lib/python3.12/site-packages/arkitekt/apps/mikro.py", line 41, in <module>
    from arkitekt.apps.herre import HerreApp
  File "/home/aschroeter/mambaforge/envs/arkitekt/lib/python3.12/site-packages/arkitekt/apps/herre.py", line 1, in <module>
    from arkitekt.apps.fakts import FaktsApp
  File "/home/aschroeter/mambaforge/envs/arkitekt/lib/python3.12/site-packages/arkitekt/apps/fakts.py", line 4, in <module>
    from fakts.grants.remote.device_code import DeviceCodeGrant
ModuleNotFoundError: No module named 'fakts.grants.remote.device_code'
```

**Comment by alexschroeter** [comment]
Until support for version 3.12 is fixed, this problem is resolved by using a version < 3.12.
